'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import Header from '@/components/Header';
import { api } from '@/lib/api';
import { inrCompact } from '@/lib/format';

interface Rtp {
  rtp: number; houseEdge: number; theoreticalRtp: number; totalRounds: number;
  avgCrash: number; maxCrash: number; totalWagered: number; totalPayout: number;
  distribution: { range: string; count: number; pct: number }[];
}

export default function RtpPage() {
  const [d, setD] = useState<Rtp | null>(null);
  useEffect(() => { api.get('/game/rtp').then((r) => setD(r.data)).catch(() => {}); }, []);

  const maxPct = d ? Math.max(...d.distribution.map((x) => x.pct), 1) : 1;

  return (
    <div className="min-h-screen">
      <Header />
      <main className="mx-auto max-w-3xl space-y-6 px-3 py-8 sm:px-4">
        <div>
          <h1 className="text-2xl font-black sm:text-3xl">📊 Game Stats & RTP</h1>
          <p className="text-sm text-white/40">Transparent return-to-player and crash distribution across all rounds.</p>
        </div>

        {!d && <p className="text-white/40">Loading…</p>}
        {d && (
          <>
            {/* headline */}
            <div className="grid gap-3 sm:grid-cols-3">
              <div className="glass p-5 text-center sm:col-span-1">
                <div className="text-[11px] uppercase tracking-widest text-white/40">Target RTP</div>
                <div className="text-4xl font-black text-win">{d.theoreticalRtp}%</div>
                <div className="mt-1 text-xs text-white/40">House edge {d.houseEdge}%</div>
              </div>
              <div className="glass flex flex-col justify-center p-5 sm:col-span-2">
                <p className="text-sm text-white/70">
                  Every round&apos;s crash point is generated by a <b>provably-fair</b> algorithm — a hashed server seed combined with a public client seed and round nonce.
                  The target RTP of <b className="text-win">{d.theoreticalRtp}%</b> means players receive ₹{d.theoreticalRtp} back for every ₹100 wagered over the long run.
                </p>
                <Link href="/fairness" className="mt-3 text-sm text-accent-glow hover:underline">🔍 Verify any round yourself →</Link>
              </div>
            </div>

            {/* stats grid */}
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              <Stat label="Total Rounds" value={d.totalRounds.toLocaleString('en-IN')} />
              <Stat label="Observed RTP" value={`${d.rtp}%`} tone="text-accent-glow" />
              <Stat label="Avg Crash" value={`${d.avgCrash}x`} />
              <Stat label="Biggest Crash" value={`${d.maxCrash}x`} tone="text-gold" />
              <Stat label="Total Wagered" value={inrCompact(d.totalWagered)} />
              <Stat label="Total Paid Out" value={inrCompact(d.totalPayout)} tone="text-win" />
            </div>

            {/* distribution */}
            <div className="glass p-5">
              <h2 className="mb-4 text-sm font-bold uppercase tracking-widest text-white/40">Crash multiplier distribution</h2>
              <div className="space-y-2.5">
                {d.distribution.map((b) => (
                  <div key={b.range} className="flex items-center gap-3 text-sm">
                    <span className="w-24 shrink-0 text-white/60">{b.range}</span>
                    <div className="h-5 flex-1 overflow-hidden rounded bg-base-700">
                      <div className="flex h-full items-center justify-end rounded bg-gradient-to-r from-accent to-accent-glow pr-2 text-[10px] font-bold text-white" style={{ width: `${Math.max(6, (b.pct / maxPct) * 100)}%` }}>
                        {b.pct}%
                      </div>
                    </div>
                    <span className="w-12 shrink-0 text-right text-xs tabular-nums text-white/40">{b.count}</span>
                  </div>
                ))}
              </div>
              <p className="mt-4 text-[11px] text-white/30">Lower multipliers occur more often by design — that&apos;s what funds the big payouts. The shape of this curve is fixed by the provably-fair math, not adjustable per round.</p>
            </div>
          </>
        )}
      </main>
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <div className="glass min-w-0 overflow-hidden p-4">
      <div className="truncate text-[11px] uppercase tracking-widest text-white/40">{label}</div>
      <div className={`mt-1 truncate text-xl font-black tabular-nums ${tone ?? 'text-white'}`}>{value}</div>
    </div>
  );
}
